name: Style

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# so only one workflow run happens for each pr/push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  style:
    name: Style
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.8"

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5

      - name: Get exact python version
        id: python-version
        run: |
          echo "python_version=$(python --version)" >> $GITHUB_ENV

      - name: Cache pre-commit environment
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: cache-pre-commit
        with:
          path: |
            ./venv/
            ~/pre-commit-cache
          key: v1-venv-precommit-${{ runner.os }}-${{ env.python_version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          uv pip install pre-commit --exclude-newer $(date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ)

      - name: Run Style Check
        run: |
          source venv/bin/activate
          PRE_COMMIT_HOME=~/pre-commit-cache pre-commit run --all-files
