name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# so only one workflow run happens for each pr/push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  style:
    name: Style
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.5"
            runs-on: ubuntu-18.04
          - python-version: "3.6"
            runs-on: ubuntu-20.04
          - python-version: "3.7"
            runs-on: ubuntu-22.04
          - python-version: "3.8"
            runs-on: ubuntu-24.04
          - python-version: "3.9"
            runs-on: ubuntu-24.04
          - python-version: "3.10"
            runs-on: ubuntu-24.04
          - python-version: "3.11"
            runs-on: ubuntu-24.04
          - python-version: "3.12"
            runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test requirements
        run: pip install -r requirements/test.txt

      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: ./run-tests.sh

      - name: Print code coverage
        run: coverage report -m | tee coverage.log

      - name: Check if coverage is 100%
        run: grep "100%" coverage.log
