name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# so only one workflow run happens for each pr/push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.5"
            runs-on: ubuntu-24.04
            image: python:3.5
          - python-version: "3.6"
            runs-on: ubuntu-24.04
            image: python:3.6
          - python-version: "3.7"
            runs-on: ubuntu-22.04
          - python-version: "3.8"
            runs-on: ubuntu-24.04
          - python-version: "3.9"
            runs-on: ubuntu-24.04
          - python-version: "3.10"
            runs-on: ubuntu-24.04
          - python-version: "3.11"
            runs-on: ubuntu-24.04
          - python-version: "3.12"
            runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ !matrix.image }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test without docker
        if: ${{ !matrix.image }}
        run: ./install-and-run-tests.sh

      - name: Test with docker
        if: ${{ matrix.image }}
        run: |
          docker run \
            --name "add-header-test" \
            -d \
            -t \
            --workdir "$GITHUB_WORKSPACE" \
            -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" \
            --entrypoint bash \
            '${{ matrix.image }}'

          docker exec "add-header-test" "$GITHUB_WORKSPACE/install-and-run-tests.sh"

      - name: Check if coverage is 100%
        run: grep "100%" coverage.log
